# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_imagebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
