# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_book_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avg_rating',
        ),
    ]
