# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_book_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagebook',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='My Photo'),
        ),
        migrations.DeleteModel(
            name='ImageBook',
        ),
    ]
