# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20170504_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.CharField(default='images.jpeg', max_length=100),
        ),
    ]
