# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_auto_20170504_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.CharField(default='images.jpg', max_length=100),
        ),
    ]
