# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='/static/bookstore/images.png', max_length=100),
        ),
    ]
