# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0025_book_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
