# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0026_auto_20170509_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Review')),
            ],
        ),
    ]
