# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0027_lastreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastreview',
            name='update_review',
            field=models.IntegerField(default=0),
        ),
    ]
