# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0028_lastreview_update_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lastreview',
            name='review',
        ),
        migrations.AddField(
            model_name='book',
            name='update_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='LastReview',
        ),
    ]
