# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0029_auto_20170514_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 8, 19, 29, 51212, tzinfo=utc)),
        ),
    ]
