# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0033_auto_20170527_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Comics', 'Comics'), ('Novel', 'Novel'), ('Psychology', 'Psychology')], max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 15, 40, 20, 96476, tzinfo=utc)),
        ),
    ]
