# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0035_auto_20170527_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bookstore.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 16, 33, 37, 753130, tzinfo=utc)),
        ),
    ]
