# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0037_auto_20170527_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='update_review',
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 17, 0, 40, 210904, tzinfo=utc)),
        ),
    ]
