# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0038_auto_20170527_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='update_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 17, 18, 49, 562936, tzinfo=utc)),
        ),
    ]
