# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0041_auto_20170527_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 6, 39, 44, 352898, tzinfo=utc)),
        ),
    ]
