# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0044_auto_20170622_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 5, 39, 48, 144767, tzinfo=utc)),
        ),
    ]
