# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 10:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0046_auto_20170622_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 10, 0, 2, 735151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.TextField(),
        ),
    ]
