# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0047_auto_20170627_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.TextField(default='B1'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 10, 2, 1, 847588, tzinfo=utc)),
        ),
    ]
