# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0048_auto_20170627_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 10, 3, 19, 481361, tzinfo=utc)),
        ),
    ]
